name: Build and push Docker image to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extraer versión del tag
      run: echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository_owner }}/brainex_web:${{ env.IMAGE_VERSION }}
        docker build -f BrainEx/Dockerfile -t $IMAGE .
        docker push $IMAGE